### PR TITLE
update install.md

### PR DESCRIPTION
**Pull request by plquera**
Included detailed explanation on running Bloqade on EC2 with images.

### CODE REVIEW

**Comment by Wang-Shengtao** [comment]
@Roger-luo Can you review the content/process? I'm happy to review the text.

**Review by Roger-luo — CHANGES_REQUESTED** [review]
the content looks good in general, but we need to include the pictures in this repo so it can be versioned. Also, I have some comments on the EC2 setup process, so we probably want to chat about this again next week. Let's schedule a meeting as early as possible next week maybe.

**Comment by lightbiaggi** [comment]
@Roger-luo  let me add them next week i have them generated i put them inside docs lets discuss it next week

**Review by Roger-luo — APPROVED** [review]
I'll fix the doc build on master later

**Pull request merged**
