### PR TITLE
Luxor backend for lattice plot

### LINKED ISSUE #196: lattice plot
@GiggleLiu the atom sizes in the lattice plot could vary a lot, as shown in the documentation lattice page: 
https://solid-journey-b55ed955.pages.github.io/dev/lattices/

Is there any way to make sure the atoms have the same size? Or at least for the default lattice (e.g. LiebLattice(), Square()), we have the same size of atoms?

### LINKED ISSUE #370: [BUG] Int128 support might to be missing for mat()
Constructing hamiltonian matrix seems to not work for more than 64 atoms. Can be useful to be able to get hamiltonians for more than 64 atoms with blockade approximation where the relevant subspace is actually much smaller.

**To Reproduce**
`ham_subspace=mat(ham, subspace)`
Doesn't work for hamiltonian and subspace built on more than 64 atoms, even with a comparably small subspace dimension.

**Error output**

> ERROR: LoadError: MethodError: no method matching ismatch(::Int128, ::Int64, ::Int64)
> Closest candidates are:
>   ismatch(::T, !Matched::T, !Matched::T) where T<:Integer at ~/.julia/packages/BitBasis/svELN/src/bit_operations.jl:190
> Stacktrace:
>    [1] (::BitBasis.var"#38#40"{Int64, Int64})(b::Int128)
>      @ BitBasis ~/.julia/packages/BitBasis/svELN/src/bit_operations.jl:319
>    [2] _main_loop(subspace_v::Vector{Int128}, map::Dict{Int128, Int128}, U::PermMatrix{ComplexF64, Int64, StaticArraysCore.SVector{2, ComplexF64}, StaticArraysCore.SVector{2, Int64}}, ctest::BitBasis.var"#38#40"{Int64, Int64}, locs::Tuple{Int64})
>      @ BloqadeExpr ~/.julia/packages/BloqadeExpr/pdOm3/src/mat.jl:82
>    [3] _cunmat(subspace_v::Vector{Int128}, map::Dict{Int128, Int128}, cbits::Tuple{}, cvals::Tuple{}, U0::LuxurySparse.SDPermMatrix{ComplexF64, Int64, Vector{ComplexF64}, Vector{Int64}}, locs::Tuple{Int64})
>      @ BloqadeExpr ~/.julia/packages/BloqadeExpr/pdOm3/src/mat.jl:65
>    [4] mat
>      @ ~/.julia/packages/BloqadeExpr/pdOm3/src/mat.jl:36 [inlined]
>    [5] (::BloqadeExpr.var"#17#18"{ComplexF64, Subspace{Int128, Vector{Int128}}})(x::PutBlock{2, 1, XGate})
>      @ BloqadeExpr ~/.julia/packages/BloqadeExpr/pdOm3/src/mat.jl:44
>    [6] _mapreduce(f::BloqadeExpr.var"#17#18"{ComplexF64, Subspace{Int128, Vector{Int128}}}, op::typeof(+), #unused#::IndexLinear, A::Vector{AbstractBlock{2}})
>      @ Base ./reduce.jl:410
>    [7] _mapreduce_dim
>      @ ./reducedim.jl:330 [inlined]
>    [8] #mapreduce#731
>      @ ./reducedim.jl:322 [inlined]
>    [9] mapreduce
>      @ ./reducedim.jl:322 [inlined]
>   [10] mat

### PR DESCRIPTION
**Pull request by GiggleLiu**
fix #370 
fix #196 

I also fixed the Int128 mat issue in this PR.

### CODE REVIEW

**Comment by GiggleLiu** [comment]
@Roger-luo I changed the Lattice plotting backend to Luxor. Wondering how can I check the documentation?

**Comment by Roger-luo** [comment]
Just build the doc locally?

**Comment by GiggleLiu** [comment]
I checked the plots locally, they look good!

**Comment by Roger-luo** [comment]
Please don't fix multiple issues in the same PR. Can you checkout a new branch?

**Comment by GiggleLiu** [comment]
You can separate it you want.

**Comment by Roger-luo** [comment]
If you don't want to separate the changes at least squash your commits into 2 commits with different msg about the change.

**Comment by GiggleLiu** [comment]
Sorry I might be a bit bad manner. I was just depressed by the time overhead to create a branch and test Bloqade locally. It often takes me more than 2 hours for a minor change. It would be great if we can make it simple. Hope in the future, the Julia overhead for running a test can be smaller.

**Comment by Roger-luo** [comment]
You don't have to run the whole test consider using 

.ci/run test <path/to/lib> 

To run single test of the corresponding package. In the future we are gonna have single test label support which would be even faster but for my experience this is already quite fast.

We need to separate the changes in PR and commit msg so that a good commit history can be maintained. Which will help people revising and reading what changes have been applied in the future.

**Comment by GiggleLiu** [comment]
The problem is, everytime I want to fix a small problem, I spend a lot of time to update my local manifest file. Is there a command to give me a clean environment so that I can run a test in vscode.

**Comment by Roger-luo** [comment]
Yes, you can use


.ci/run dev <path/to/your/env>

To change the dependency to be local lib packages. So that you can also run single tests in vscode.

**Comment by GiggleLiu** [comment]
> Yes, you can use
> 
> .ci/run dev <path/to/your/env>
> 
> To change the dependency to be local lib packages. So that you can also run single tests in vscode.

But you can not update the .ci env with that. It is a bootstrap issue.

**Comment by Roger-luo** [comment]
> But you can not update the .ci env with that. It is a bootstrap issue.

why do you need to update `.ci` env? it's only used by the CLI command and has no deps on package inside this repo, it should be only updated once?

**Comment by Roger-luo** [comment]
OK, I don't think I'm gonna have time to split this, let's just hope we don't need to check this git blame in the future and let it go, but next time if you really have trouble running test pls let me know. I can tell you the fastest workflow.

**Pull request merged**
