### PR TITLE
Examples for 3-level simulation

### PR DESCRIPTION
**Pull request by ChenZhao44**
These examples are from Corbin's pulse sequence zoo.

### CODE REVIEW

**Comment by Roger-luo** [comment]
I think it should be `nqudits` instead of `nqubits` which is causing tests to fail

**Comment by ChenZhao44** [comment]
> I think it should be `nqudits` instead of `nqubits` which is causing tests to fail

The bug of `nqubits` has been fixed in the part of BloqadeODE in this PR. However, it still failed because CI doesn't run the code based on the latest version of BloqadeODE. Should I submit another PR to fix the `nqubits` part seperately?

**Comment by Roger-luo** [comment]
That's strange CI should use the latest change in a branch by dev then.

**Comment by ChenZhao44** [comment]
I guess it happened because CI run the test according to the Project.toml file in the test of BloqadeExpr. And it just used the latest released version or master version instead of the dev version for testing.

**Comment by Roger-luo** [comment]
Err that shouldn't happen. Let me take a look before merging this PR

**Comment by Roger-luo** [comment]
I think you put the tests in wrong module, the ODE tests should be in the ODE module not the BloqadeExpr, this is why the test is not recognizing the dependencies, you can easily reproduce the same error locally by just running `]test`

**Pull request closed without merging**
