### PR TITLE
Added minor suggestions to text for MIS tutorial

### PR DESCRIPTION
**Pull request by johnzl-777**

### CODE REVIEW

**Comment by Wang-Shengtao** [comment]
The file diff seems to be everything?

**Comment by johnzl-777** [comment]
The .gitignore seems to exclude all of the tutorials that require executing a .jl file (versus the rest of the docs that just render .md files). I think I ended up force adding this (probably not good practice 😅 ), hence why the diff just gives the whole file. @Roger-luo is there a better way for me to provide suggestions for the MIS tutorial?

Also notice that GenericTensorNetworks is giving all these warnings, I'm using Julia 1.8.2, don't know if that has anything to do with it.

**Comment by Roger-luo** [comment]
The tutorials are generated through Literate, you should store them in Literate format so that we can convert things to notebooks and markdown not just markdown.

It seems you are manually writing the generated markdown file...

**Comment by Roger-luo** [comment]
> Also notice that GenericTensorNetworks is giving all these warnings, I'm using Julia 1.8.2, don't know if that has anything to do with it.

Well I guess @GiggleLiu is a big fan of defining unused type params, we have a bunch in Yao as well ;-) but he is busy with JuliaCN meetup recently, maybe you can do him a favor by removing those unused type in a PR if you get time. Or we can just wait for someone to do it, since its not a big issue.

**Comment by johnzl-777** [comment]
> The tutorials are generated through Literate, you should store them in Literate format so that we can convert things to notebooks and markdown not just markdown.
> 
> It seems you are manually writing the generated markdown file...

Ah got it! Apologies on my end, I thought it was all self-contained in the .md 😅

**Comment by johnzl-777** [comment]
> > Also notice that GenericTensorNetworks is giving all these warnings, I'm using Julia 1.8.2, don't know if that has anything to do with it.
> 
> Well I guess @GiggleLiu is a big fan of defining unused type params, we have a bunch in Yao as well ;-) but he is busy with JuliaCN meetup recently, maybe you can do him a favor by removing those unused type in a PR if you get time. Or we can just wait for someone to do it, since its not a big issue.

Can do!

**Comment by johnzl-777** [comment]
Closing this PR in favor of starting a new one that properly modifies the Literate formatted files for the tutorials (versus the outputted Markdown!)

**Pull request closed without merging**
