### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by GiggleLiu**

### CODE REVIEW

**Comment by GiggleLiu** [comment]
@Roger-luo I have updated all dependencies, without testing GPU code. Do you have any idea how to get the GPU code tested? or can you please help test the GPU code locally?

**Review by Roger-luo — APPROVED** [review]
I think CUDA is good. Let's merge this first. Also FYI. I don't think QuEra has bandwidth maintaining this package anymore. We are guiding people to use bloqade-python for analog computing with device.

**Comment by GiggleLiu** [comment]
I understand, I have a few students using Bloqade to learn Rydberg atoms array emulation. Before moving to maintenance stage, I may also want to submit a PR to change the plotting backend to CairoMakie in near future, do you also agree about this proposal?

**Comment by Roger-luo** [comment]
Feel free to change anything if you want. It's more just we won't have bandwidth working on any features at the moment.

**Pull request merged**
