### PR TITLE
Fix ODE compatibility issues for now

### PR DESCRIPTION
**Pull request by johnzl-777**
in 1.9 the latest version of OrdinaryDiffEq seems to have compatibility issues with our custom `__init` function. I've set the compatibility to the last compatible version which seems to be anything before 6.58.0.

### CODE REVIEW

**Comment by weinbe58** [comment]
Seems like there is still an issue related to `__init` in BloqadeKrylov tests. Maybe we need to lower the version more?

**Review by weinbe58 — CHANGES_REQUESTED** [review]
Seems like there is still an issue related to `__init` in BloqadeKrylov tests. Maybe we need to lower the version more?

**Comment by ArbitRandomUser** [comment]
did BlockadeKrylov fail because its test environment still uses BloqadeODE from the registry ?

**Comment by ArbitRandomUser** [comment]
BloqadeExpr exports `SumOfLoop` now which the registry package does not have yet. This also causes tests to fail.

setting up a custom test environment (`dev`ing packages that Project.toml includes from `lib`) and manually `include("runtests.jl")` in it causes one more error with ForwardDiff.jl . which is fixed by updating ForwardDiff to v0.10.36.

the environment i used for running the test ...
```
Status `~/workspace/Bloqade.jl/lib/BloqadeKrylov/test/Project.toml`
  [bd27d05e] BloqadeExpr v0.1.14 `../../BloqadeExpr`
  [bd27d05e] BloqadeKrylov v0.1.8 `..`
  [bd27d05e] BloqadeLattices v0.1.8 `../../BloqadeLattices`
  [bd27d05e] BloqadeODE v0.1.11 `../../BloqadeODE`
  [bd27d05e] BloqadeWaveforms v0.1.7 `../../BloqadeWaveforms`
  [d4d017d3] ExponentialUtilities v1.25.0
  [f6369f11] ForwardDiff v0.10.36
  [5872b779] Yao v0.8.11
  [e600142f] YaoArrayRegister v0.9.7
  [bd27d05e] YaoSubspaceArrayReg v0.1.8
  [37e2e46d] LinearAlgebra
  [9a3f8284] Random
  [2f01184e] SparseArrays
  [8dfed614] Test
```

**Comment by weinbe58** [comment]
The problem is that one of the tests depends on BloqadeODE which is currently broken by the compatibility. Its a test dependency so that "dev"ing the local package doesn't cover that dependency so I think we need to just merge this first and release a new version of BloqadeODE before we can fix the CI.

**Pull request merged**
